name: Publish package to pypi

on:
  push:
    branches: [main]
    paths:
      - "src/coastal_dynamics/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  build_and_publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@b09ef9b599704322748535812ca03efb2625677b # v2
        with:
          environment-file: ci/envs/311-package.yaml

      - name: Build package
        run: |
          poetry install
          poetry build

      # - name: Publish package distributions to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # release/v1
      #   with:
      #     repository-url: https://test.pypi.org/legacy/

      # # Test install from TestPyPI
      # - name: Test install from TestPyPI
      #   run: |
      #     pip install \
      #     --index-url https://test.pypi.org/simple/ \
      #     --extra-index-url https://pypi.org/simple \
      #     coastal-dynamics

      # Publish to PyPI
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # release/v1
